#!/usr/bin/env node
'use strict'

const fs = require('node:fs')
const path = require('node:path')
const { createHash } = require('node:crypto')

const input = process.argv[2]
const output = process.argv[3] || 'main.crdt'
const bakedOutput = process.argv[4] || 'src/baked-bricks.ts'
if (!input) {
  console.error('usage: node scripts/gen-scene-crdt.ts SNAPSHOT [CRDT] [BAKED_MODULE]')
  process.exit(2)
}

function writeAtomic(file, data) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  const temporary = `${file}.tmp-${process.pid}`
  let fd
  try {
    fd = fs.openSync(temporary, 'w', 0o644)
    fs.writeFileSync(fd, data)
    fs.fsyncSync(fd)
    fs.closeSync(fd)
    fd = undefined
    fs.renameSync(temporary, file)
  } catch (error) {
    if (fd !== undefined) fs.closeSync(fd)
    try { fs.unlinkSync(temporary) } catch {}
    throw error
  }
}

// Brick metadata is scene-only (the renderer never reads it), so it ships in the bundle
// instead of main.crdt: renderers skip unknown components but still parse and warn per entity.
const FIRST_ENTITY = 512

function bakedModule(records, revision) {
  const by = []
  const byIndex = new Map()
  const rows = records.map((record) => {
    if (!byIndex.has(record.by)) {
      byIndex.set(record.by, by.length)
      by.push(record.by)
    }
    return [record.id, record.defIdx, record.a0, record.b0, record.ys0, record.rotK,
      record.color, record.thick, byIndex.get(record.by), record.at]
  })
  return [
    `// Generated by scripts/gen-scene-crdt.ts from snapshot revision ${revision}. Do not edit.`,
    '// Row i describes entity BAKED_FIRST_ENTITY + i in main.crdt:',
    '// [id, defIdx, a0, b0, ys0, rotK, color, thick, byIndex, at]',
    `export const BAKED_FIRST_ENTITY = ${FIRST_ENTITY}`,
    `export const BAKED_BY: readonly string[] = ${JSON.stringify(by)}`,
    'export const BAKED_BRICKS: readonly (readonly number[])[] = [',
    ...rows.map((row) => `  ${JSON.stringify(row)},`),
    ']',
    ''
  ].join('\n')
}

async function main() {
  const Core = require('../src/hexbrick-core.ts')
  const Config = await import('../src/scene-config.ts')
  const { BrickWorld, decode } = await import('../service/world.ts')
  const { BUILTIN_SPECS, CrdtWriter, IDS } = await import('../src/raw/protocol.ts')
  const codecs = new Map(BUILTIN_SPECS.map((spec) => [spec[1], spec[2]]))
  const snapshotBytes = fs.readFileSync(input)
  const snapshot = JSON.parse(snapshotBytes)
  if (!snapshot || typeof snapshot !== 'object' ||
      snapshot.version !== undefined && snapshot.version !== 1 && snapshot.version !== 2)
    throw new Error('snapshot has an unsupported root or version')
  if (!Number.isSafeInteger(snapshot.revision) || snapshot.revision < 0)
    throw new Error('snapshot.revision must be a non-negative safe integer')
  if (!Array.isArray(snapshot.bricks) || !Array.isArray(snapshot.deleted))
    throw new Error('snapshot.bricks and snapshot.deleted must be arrays')

  const records = snapshot.bricks.map(decode)
  if (records.some((record) => record === null)) throw new Error('snapshot contains an invalid brick tuple')
  records.sort((a, b) => a.id - b.id)
  const deleted = new Set()
  for (const id of snapshot.deleted) {
    if (!Number.isSafeInteger(id) || id <= 0 || deleted.has(id))
      throw new Error(`invalid or duplicate tombstone ${id}`)
    deleted.add(id)
  }
  const world = new BrickWorld()
  for (const record of records) {
    if (deleted.has(record.id)) throw new Error(`brick ${record.id} is also tombstoned`)
    if (!world.add(record, true)) throw new Error(`brick ${record.id} collides, is off-grid, or is outside the parcel`)
    const model = path.resolve(`models/brick-${record.defIdx}-${record.color}.glb`)
    if (!fs.existsSync(model)) throw new Error(`missing model ${model}`)
  }

  const writer = new CrdtWriter(Math.max(4096, records.length * 228))
  const components = [
    [IDS.Transform, (record) => {
      const point = Core.vertexPos(record.a0, record.b0)
      const yaw = -record.rotK * Math.PI / 6
      return {
        position: { x: Config.ORIGIN.x + point.x, y: Config.BRICK_BASE_Y + record.ys0 * Core.HSUB, z: Config.ORIGIN.z + point.z },
        rotation: { x: 0, y: Math.sin(yaw), z: 0, w: Math.cos(yaw) },
        scale: { x: 1, y: record.thick * Core.HSUB - Config.THICK_GAP, z: 1 },
        parent: 0
      }
    }],
    [IDS.GltfContainer, (record) => ({
      src: `models/brick-${record.defIdx}-${record.color}.glb`,
      visibleMeshesCollisionMask: 3,
      invisibleMeshesCollisionMask: 0
    })]
  ]
  for (const [id, value] of components)
    records.forEach((record, index) => writer.put(FIRST_ENTITY + index, id, 0, codecs.get(id).encode(value(record))))

  const crdt = writer.take()
  const baked = bakedModule(records, snapshot.revision)
  writeAtomic(output, crdt)
  writeAtomic(bakedOutput, baked)
  const sha256 = (value) => createHash('sha256').update(value).digest('hex')
  console.log(JSON.stringify({
    snapshot: input,
    snapshotSha256: sha256(snapshotBytes),
    revision: snapshot.revision,
    bricks: records.length,
    crdt: output,
    crdtBytes: crdt.length,
    crdtSha256: sha256(crdt),
    baked: bakedOutput,
    bakedBytes: Buffer.byteLength(baked),
    bakedSha256: sha256(baked)
  }, null, 2))
}

main().catch((error) => {
  console.error(error?.stack ?? error)
  process.exitCode = 1
})
